Add coins to teams and user add/remove route
lugvitc/pwncore pull request #12
Opened 2023-12-22 06:14 UTC by mradigen

This PR adds:
- Field coins to each team, defaulting to 0 on creation.
- Everytime a hint is requested, an amount is deducted from the team's coins. (amount can be set in `config.hint_penalty`)
- Team will not be allowed to view hints if they do not have the enough coins to do so.
- `/api/team/add` route creates a user and adds them to a given team. Returns 403 if user already exists in another team.
- `/api/team/remove` route removes a user from a team. Returns 403, if user is not a part of the selected team.

2023-12-22 06:19 UTC, mradigen commented
@Meetesh-Saini How will we be incrementing the coins? Does solving the CTF reward the team with coins as well as leaderboard points?

2023-12-23 08:29 UTC, WizzyGeek commented
> @Meetesh-Saini How will we be incrementing the coins? Does solving the CTF reward the team with coins as well as leaderboard points?

In the 1 week period, it reward them with just coins for solving challenges

2023-12-24 12:09 UTC, mradigen commented
> > @Meetesh-Saini How will we be incrementing the coins? Does solving the CTF reward the team with coins as well as leaderboard points?
> 
> In the 1 week period, it rewards them with just coins for solving challenges

Got it. I'll implement an optional field called `coins` to `Problem`. The field can be set for the first week challenges, while the challenges on the event day would have a coin reward of 0.

2023-12-24 17:25 UTC, WizzyGeek approved these changes
the team's add and remove route needs to check the amount of Users in the team and other stuff, but I am not clear on the business logic for that functionality right now to specify the details myself

2023-12-27 08:58 UTC, WizzyGeek commented
@mradigen get this merged asap, contact @Meetesh-Saini to merge it for you

2024-01-08 18:40 UTC, WizzyGeek requested changes

2024-01-08 18:40 UTC, WizzyGeek commented on src/pwncore/models/ctf.py
> +    coins = fields.IntField(default=0)
Inherit from Problems

2024-01-09 11:39 UTC, WizzyGeek approved these changes

2024-01-09 11:51 UTC, mradigen commented
The recent few commits add the following changes:
- Pre-event routes under `/api/ctf/pre/` which replicates `/api/ctf/`
- Splits event problem and pre-event problem models under `Problem` and `PreEventProblem` that inherit `BaseProblem`
- `Problem_Pydantic` has been changed to `BaseProblem_Pydantic`
- Normalizes User.tag using `.strip().casefold()`
- Coins under `PreEventProblem` is named as `points` (since it inherits from `BaseProblem`)
- Added `/api/leaderboard`

2024-01-09 12:07 UTC, WizzyGeek commented
@mradigen ready to merge?

2024-01-09 13:19 UTC, WizzyGeek commented on src/pwncore/routes/leaderboard.py
> +        leaderboard[team.name] = sum(problems_solved_by_team)  # type: ignore[arg-type]
Use `Team.all().annotate(team_points = Sum("solvedproblems__problem__points"))`
adds a team_points field in the Result

2024-01-09 13:43 UTC, WizzyGeek commented on src/pwncore/routes/leaderboard.py
> +        leaderboard[team.name] = sum(problems_solved_by_team)  # type: ignore[arg-type]
![image](https://github.com/lugvitc/pwncore/assets/51919967/faae6a54-1d5a-4838-8819-21880f5bbb2e)
Working fine

2024-01-10 17:12 UTC, Meetesh-Saini approved these changes

2024-01-10 17:12 UTC, merged