Add configuration for tox, poetry and mypy
lugvitc/pwncore pull request #3
Opened 2023-11-04 21:35 UTC by WizzyGeek

Also changed the project structure.

Have a look and let me know if it looks good.

@mradigen 
@Meetesh-Saini

2023-11-05 03:41 UTC, mradigen approved these changes
Everything else LGTM

2023-11-05 03:41 UTC, mradigen commented on pyproject.toml
Wouldn't we have to include `py.typed` in `pyproject.toml` if we're making pwncore a package?

2023-11-05 06:26 UTC, WizzyGeek commented on pyproject.toml
Poetry includes everything in the package source tree, no additional includes needed 👍🏼

2023-11-05 13:15 UTC, Meetesh-Saini requested changes

2023-11-05 13:15 UTC, Meetesh-Saini commented on src/pwncore/routes/__init__.py
Change the import to absolute

2023-11-05 13:21 UTC, WizzyGeek commented
All done, GTG @Meetesh-Saini @mradigen

2023-11-05 13:21 UTC, WizzyGeek commented
Tox workflow is broken will create issue for that

2023-11-06 06:42 UTC, Meetesh-Saini approved these changes
Looks good to me

2023-11-06 11:15 UTC, nexxeln approved these changes

2023-11-06 16:34 UTC, merged