Add round 2 routes along with the admin interface
lugvitc/pwncore pull request #30
Opened 2024-01-27 17:36 UTC by WizzyGeek

Adds the required routes and models for round2

2024-01-27 17:57 UTC, mradigen requested changes

2024-01-27 17:57 UTC, mradigen commented on src/pwncore/models/round2.py
> +        exclude = ["docker_id", "flag", "meta_team"]
Let me know if I understand this correctly:

Each MetaTeam will have a single docker container for one CTF

The DB will have 10 entries with the same docker_id each with a different MetaTeam

Once a MetaTeam finds the flag, the container with the victim's docker_id and attacker's MetaTeam is marked as solved.


If the above mentioned is the case, then docker_id cannot be pk.
If we store a single container entry per docker container, how would we track which teams have exploited a victim's container? (since we're allowing multiple teams to attack on one container)

2024-01-27 17:57 UTC, mradigen commented on src/pwncore/routes/admin.py
> +async def _create_container(prob: R2Problem, mteam: MetaTeam):
Need to make this atomic

2024-01-27 17:57 UTC, mradigen commented on src/pwncore/routes/round2.py
> +async def r2_submit(container_id: int, flag: Flag, jwt: RequireJwt, response: Response):
Would be better to make this atomic as well

2024-01-27 18:09 UTC, WizzyGeek commented on src/pwncore/models/round2.py
> +        exclude = ["docker_id", "flag", "meta_team"]
> If the above mentioned is the case, then docker_id cannot be pk.
Don't know about the lines above this, but the last line is an error adding R2AttackRecord model to fix

2024-01-28 06:28 UTC, Meetesh-Saini approved these changes

2024-01-28 06:37 UTC, mradigen approved these changes

2024-01-28 06:40 UTC, merged